# docker-compose.yml
version: "3.8"

services:
  # Primary PostgreSQL Node
  postgres_primary:
    image: postgres:14
    container_name: postgres_primary
    environment:
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./primary_data:/var/lib/postgresql/data
      - ./primary_config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./primary_config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - postgres-cluster

  # Replica Node 1
  postgres_replica1:
    image: postgres:14
    container_name: postgres_replica1
    environment:
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - ./replica1_data:/var/lib/postgresql/data
      - ./replica1_config/recovery.signal:/var/lib/postgresql/data/recovery.signal
    depends_on:
      - postgres_primary
    networks:
      - postgres-cluster

  # Replica Node 2
  postgres_replica2:
    image: postgres:14
    container_name: postgres_replica2
    environment:
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"
    volumes:
      - ./replica2_data:/var/lib/postgresql/data
      - ./replica2_config/recovery.signal:/var/lib/postgresql/data/recovery.signal
    depends_on:
      - postgres_primary
    networks:
      - postgres-cluster

  # etcd for coordination
  etcd:
    image: quay.io/coreos/etcd:v3.4.13
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
    networks:
      - postgres-cluster

  # HAProxy for load balancing
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "5000:5000"
    depends_on:
      - postgres_primary
      - postgres_replica1
      - postgres_replica2
    networks:
      - postgres-cluster

networks:
  postgres-cluster:
    driver: bridge
